# make it explicit that we favor the new container-based travis workers
sudo: false

language: python
python:
  - 2.7
  - 3.4
notifications:
  email: false

addons:
  apt:
    packages:
      - libatlas-dev
      - python-scipy

install:
  - python setup.py install
# Run test
script:
  - nosetests --with-cov --cov opengrid --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc