language: python
python:
  - 2.7
  - 3.4
notifications:
  email: false

sudo: required

# Setup anaconda
before_install:
  - sudo apt-get install python-numpy python-scipy

# Run test
script:
  - nosetests --with-cov --cov opengrid --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc